version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
    restart: unless-stopped
    networks:
      - papo-reto-network

networks:
  papo-reto-network:
    name: papo-reto-network
    driver: bridge
